### ISSUE TITLE
Refresh Rate from API response not honoured. 

### ISSUE THREAD

**Issue by ronakjain90** [usetrmnl/firmware#2]
Hi - I got my test TRMNL device.

Initially the TMRNL refreshes the screen every 15 mins which is expected, however on the API response, I made it to refresh faster. However, I can see that the TRMNL device is still not honouring the refresh rate from API response, and it's still defaulting to global  default.

https://github.com/usetrmnl/firmware/blob/a1568e1bb43702b630a5db0a6bab48ae734390e1/src/bl.cpp#L583

**Comment by ryanckulp** [comment]
fixed via 1.2.4
