### ISSUE TITLE
Require confirmation during "soft reset"

### ISSUE THREAD

**Issue by ryanckulp** [usetrmnl/firmware#30]
our WiFi portal has a "Soft reset" button which, when pressed, immediately performs a soft reset.

users should be made aware what exactly this does, and be required to confirm it (modal, new screen, etc).

something like:

"Are you sure? Soft resetting your TRMNL device will delete all WiFi credentials, clear your Device's ID, and reset your API key."

cc @paw3lx

**Comment by paw3lx** [comment]
Sure, good idea. I can work on that.

**Comment by GoReNeY** [comment]
Done in #39
