### ISSUE TITLE
Feature Ask: Configurable Sleep Schedule

### ISSUE THREAD

**Issue by JackDDavis** [usetrmnl/firmware#46]
Would like the ability to configure sleep schedule. The default option for sleep schedule is 10p-8a though this does not always align to a user's schedule. This may prompt more users to enable thereby reducing the amount of pinging across all devices while extending battery life for end user TRMNL devices.

**Comment by ryanckulp** [comment]
thanks Jack. we will get this done at the web app (vs firmware) layer, but i'll keep this issue open until it's live.

**Comment by JackDDavis** [comment]
Great news. Question: Is there a better place/separate repo for submitting/tracking web app specific asks?

**Comment by ronakjain90** [comment]
Hi @JackDDavis - This is a good place to start: https://usetrmnl.com/roadmap

**Comment by ryanckulp** [comment]
@JackDDavis custom sleep schedules are now live, cheers.

![image](https://github.com/user-attachments/assets/24d92cf4-163d-4f25-91f2-df1ad4c460a3)

**Comment by JackDDavis** [comment]
Hey Ryan. In testing alternative sleep schedules, it works successfully though the display still lists 8am during sleep
