### ISSUE TITLE
Beautify the WiFi setup portal

### ISSUE THREAD

**Issue by ryanckulp** [usetrmnl/firmware#5]
we currently use this project to provide users an easy WiFi handshake between their local network and the device:
https://github.com/tzapu/WiFiManager

![image](https://github.com/usetrmnl/firmware/assets/3083888/b8eae477-2c47-4a79-967d-89839162ad5a)

let's migrate to this library and make a custom web portal that matchs our brand:
https://github.com/CDFER/Captive-Portal-ESP32

**Comment by paw3lx** [comment]
I talked to @ryanckulp about that issue. I'm investigating what are the options. The proposed library (https://github.com/CDFER/Captive-Portal-ESP32) is actually a simple captive portal (basic webpage). It would require development of the WiFi configuration portal, managing of credentials etc. 
I'm looking for another libraries, e.g. https://github.com/ayushsharma82/ESPConnect which looks something that we need - simple wifi captive portal, but I don't like setup of the portal part. 

It might be that the simplest approach would be to not use any library and build custom WiFi portal, so we can style it as we want - IMO it also shouldn't require that much time to develop.

**Comment by stevekennedyuk** [comment]
https://github.com/revk/ESP32-RevK
